"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";

import { csvRecords } from "@/lib/csv";
import { ApplicationError } from "@/lib/errors";
import { requireBranchAccess } from "@/modules/auth/authorization";
import { hasPermission } from "@/modules/auth/permissions";
import { cancelInventoryCount, createInventoryCount, importInventoryCountEntries, postInventoryCount, reopenInventoryCount, saveInventoryCountEntries, startInventoryCount, submitInventoryCountForReview } from "./count-service";

const countRoles = ["OWNER","ADMIN","BRANCH_MANAGER","STOREKEEPER"] as const;
const postingRoles = ["OWNER","ADMIN","BRANCH_MANAGER"] as const;
const identitySchema = z.object({branchId:z.uuid(),countId:z.uuid()});

function countError(error:unknown){return encodeURIComponent(error instanceof ApplicationError?error.message:"Inventory count operation failed.");}
function canUse(access:{role:Parameters<typeof hasPermission>[0];permissions:string[]|null},roles:readonly string[]){return roles.includes(access.role)&&hasPermission(access.role,"inventory:manage",access.permissions);}

async function parseCountCsv(formData:FormData){const file=formData.get("file");if(!(file instanceof File)||file.size===0||file.size>1_500_000||!file.name.toLowerCase().endsWith(".csv"))throw new ApplicationError("Choose a CSV file no larger than 1.5 MB.","INVALID_COUNT_FILE");const records=csvRecords(await file.text(),["sku","counted_quantity"],5_000);const populated=records.filter((record)=>record.values.counted_quantity!=="");const entries=populated.map((record)=>{if(!/^\d+$/.test(record.values.counted_quantity))throw new ApplicationError(`Row ${record.rowNumber} has an invalid counted quantity.`,"INVALID_COUNT_FILE");const countedQuantity=Number(record.values.counted_quantity);if(!Number.isSafeInteger(countedQuantity)||countedQuantity>2_000_000_000)throw new ApplicationError(`Row ${record.rowNumber} has a counted quantity that is too large.`,"INVALID_COUNT_FILE");return{sku:record.values.sku.replace(/^'(?=[=+\-@])/,""),countedQuantity,notes:record.values.notes||undefined};});if(!entries.length)throw new ApplicationError("The CSV has no populated counted quantities.","INVALID_COUNT_FILE");return entries;}

export async function createInventoryCountAction(formData:FormData){const parsed=z.object({branchId:z.uuid(),notes:z.string().trim().max(500).optional()}).safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/inventory/counts/new?error=Check+the+count+details.");const access=await requireBranchAccess(parsed.data.branchId);if(!canUse(access,countRoles))redirect("/inventory");let countId:string;try{const count=await createInventoryCount({businessId:access.business.id,branchId:parsed.data.branchId,userId:access.user.id,notes:parsed.data.notes});countId=count.id;}catch(error){redirect(`/inventory/counts/new?error=${countError(error)}`);}redirect(`/inventory/counts/${countId}`);}

export async function startInventoryCountAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,countRoles))redirect("/inventory");try{await startInventoryCount({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}revalidatePath(`/inventory/counts/${parsed.countId}`);redirect(`/inventory/counts/${parsed.countId}`);}

export async function saveInventoryCountEntriesAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,countRoles))redirect("/inventory");const ids=[...new Set(formData.getAll("itemId").map(String))];const entries=ids.flatMap((itemId)=>{const quantity=String(formData.get(`quantity_${itemId}`)??"").trim();if(quantity==="")return[];const countedQuantity=Number(quantity);if(!z.uuid().safeParse(itemId).success||!/^\d+$/.test(quantity)||!Number.isSafeInteger(countedQuantity)||countedQuantity>2_000_000_000)redirect(`/inventory/counts/${parsed.countId}?error=One+or+more+quantities+are+invalid.`);return[{itemId,countedQuantity,notes:String(formData.get(`notes_${itemId}`)||"")}];});if(!entries.length)redirect(`/inventory/counts/${parsed.countId}?error=Enter+at+least+one+physical+quantity.`);try{await saveInventoryCountEntries({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id,entries});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}revalidatePath(`/inventory/counts/${parsed.countId}`);redirect(`/inventory/counts/${parsed.countId}?saved=1`);}

export async function importInventoryCountAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,countRoles))redirect("/inventory");try{const entries=await parseCountCsv(formData);await importInventoryCountEntries({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id,entries});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}revalidatePath(`/inventory/counts/${parsed.countId}`);redirect(`/inventory/counts/${parsed.countId}?imported=1`);}

export async function createInventoryCountFromCsvAction(formData:FormData){const branchId=z.uuid().parse(formData.get("branchId"));const access=await requireBranchAccess(branchId);if(!canUse(access,countRoles))redirect("/inventory");let countId:string|undefined;try{const entries=await parseCountCsv(formData);const count=await createInventoryCount({businessId:access.business.id,branchId,userId:access.user.id,notes:"Created from inventory CSV import"});countId=count.id;await startInventoryCount({businessId:access.business.id,branchId,countId:count.id,userId:access.user.id});await importInventoryCountEntries({businessId:access.business.id,branchId,countId:count.id,userId:access.user.id,entries});}catch(error){redirect(countId?`/inventory/counts/${countId}?error=${countError(error)}`:`/inventory/import?error=${countError(error)}`);}redirect(`/inventory/counts/${countId}?imported=1`);}

export async function submitInventoryCountForReviewAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,countRoles))redirect("/inventory");try{await submitInventoryCountForReview({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}redirect(`/inventory/counts/${parsed.countId}`);}
export async function reopenInventoryCountAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,postingRoles))redirect("/inventory");try{await reopenInventoryCount({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}redirect(`/inventory/counts/${parsed.countId}`);}
export async function postInventoryCountAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,postingRoles))redirect("/inventory");try{await postInventoryCount({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}revalidatePath("/inventory");redirect(`/inventory/counts/${parsed.countId}?posted=1`);}
export async function cancelInventoryCountAction(formData:FormData){const parsed=identitySchema.parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!canUse(access,postingRoles))redirect("/inventory");try{await cancelInventoryCount({businessId:access.business.id,branchId:parsed.branchId,countId:parsed.countId,userId:access.user.id});}catch(error){redirect(`/inventory/counts/${parsed.countId}?error=${countError(error)}`);}redirect(`/inventory/counts/${parsed.countId}`);}
