import { asc, eq } from "drizzle-orm";
import { Plus } from "lucide-react";
import Link from "next/link";
import { db } from "@/db/client";
import { categories, products } from "@/db/schema";
import { formatMoney } from "@/lib/money";
import { requirePermission } from "@/modules/auth/authorization";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; status?: string }> }) { const access = await requirePermission("product:manage"); const params = await searchParams; const [records, categoryRecords] = await Promise.all([db.select({ id: products.id, name: products.name, sku: products.sku, barcode: products.barcode, price: products.sellingPrice, cost: products.costPrice, unit: products.unit, active: products.active, category: categories.name, categoryId: products.categoryId }).from(products).leftJoin(categories, eq(categories.id, products.categoryId)).where(eq(products.businessId, access.business.id)).orderBy(asc(products.name)), db.select().from(categories).where(eq(categories.businessId, access.business.id)).orderBy(asc(categories.name))]); const query=(params.q||"").trim().toLowerCase(); const filtered=records.filter((product)=>(!query||`${product.name} ${product.sku} ${product.barcode||""}`.toLowerCase().includes(query))&&(!params.category||product.categoryId===params.category)&&(!params.status||(params.status==="active"?product.active:!product.active))); return <><header className="topbar"><div><p className="eyebrow">Catalogue</p><h1>Products</h1><p>Central product catalogue for every branch.</p></div><Link className="button primary inline-button" href="/products/new"><Plus size={17}/> New product</Link></header><main className="page"><form className="filter-bar"><label>Search<input name="q" defaultValue={params.q} placeholder="Name, SKU or barcode"/></label><label>Category<select name="category" defaultValue={params.category||""}><option value="">All categories</option>{categoryRecords.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Status<select name="status" defaultValue={params.status||""}><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="button secondary">Apply</button></form><section className="surface table-surface"><table><thead><tr><th>Product</th><th>SKU / Barcode</th><th>Category</th><th>Cost</th><th>Price</th><th>Status</th></tr></thead><tbody>{filtered.map((p) => <tr key={p.id}><td><Link href={`/products/${p.id}/edit`}><strong>{p.name}</strong></Link><small>Per {p.unit}</small></td><td><code>{p.sku}</code><small>{p.barcode || "No barcode"}</small></td><td>{p.category || "Uncategorised"}</td><td>{formatMoney(p.cost, access.business.currency)}</td><td><strong>{formatMoney(p.price, access.business.currency)}</strong></td><td><span className={p.active ? "pill active" : "pill"}>{p.active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-state">No matching products.</div>}</section></main></>; }
