"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { parseMoney } from "@/lib/money";
import { withToast } from "@/lib/toast";
import { requireBranchAccess, requirePermission } from "@/modules/auth/authorization";
import { hasPermission } from "@/modules/auth/permissions";
import { createPurchaseOrder, createSupplier, placePurchaseOrder, receivePurchaseOrder, recordPurchasePayment } from "./service";

const optional=(max:number)=>z.string().trim().max(max).optional();
function purchasingAccess(access:Awaited<ReturnType<typeof requirePermission>>,manage=false){return hasPermission(access.role,manage?"purchasing:manage":"purchasing:read",access.permissions);}
function parseJson(value:string){try{return JSON.parse(value) as unknown;}catch{return null;}}

export async function createSupplierAction(formData:FormData){const parsed=z.object({name:z.string().trim().min(2).max(150),contactName:optional(120),phone:optional(40),email:z.union([z.literal(""),z.email()]).optional(),address:optional(500),taxId:optional(80),paymentTermsDays:z.coerce.number().int().min(0).max(365),leadTimeDays:z.coerce.number().int().min(0).max(365),notes:optional(500)}).safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/purchasing/suppliers/new?error=Check+the+supplier+details.");const access=await requirePermission("purchasing:manage");if(!purchasingAccess(access,true))redirect("/overview");await createSupplier({businessId:access.business.id,userId:access.user.id,...parsed.data});revalidatePath("/purchasing");redirect(withToast("/purchasing/suppliers","Supplier created."));}

const lineSchema=z.object({productId:z.uuid(),quantity:z.number().int().positive(),unitCost:z.string().regex(/^\d+(\.\d{1,2})?$/)});
export async function createPurchaseOrderAction(formData:FormData){const parsed=z.object({branchId:z.uuid(),supplierId:z.uuid(),expectedAt:z.union([z.literal(""),z.iso.date()]).optional(),notes:optional(500),lines:z.string()}).safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/purchasing/new?error=Check+the+order+details.");const linesResult=z.array(lineSchema).min(1).max(200).safeParse(parseJson(parsed.data.lines));if(!linesResult.success)redirect("/purchasing/new?error=Add+valid+order+items.");const access=await requireBranchAccess(parsed.data.branchId);if(!hasPermission(access.role,"purchasing:manage",access.permissions))redirect("/overview");const order=await createPurchaseOrder({businessId:access.business.id,branchId:parsed.data.branchId,supplierId:parsed.data.supplierId,userId:access.user.id,expectedAt:parsed.data.expectedAt?new Date(`${parsed.data.expectedAt}T12:00:00Z`):undefined,notes:parsed.data.notes,lines:linesResult.data.map(x=>({...x,unitCost:parseMoney(x.unitCost)}))});revalidatePath("/purchasing");redirect(withToast(`/purchasing/${order.id}`,"Purchase order created as draft."));}

export async function placePurchaseOrderAction(formData:FormData){const orderId=z.uuid().parse(formData.get("orderId"));const branchId=z.uuid().parse(formData.get("branchId"));const access=await requireBranchAccess(branchId);if(!hasPermission(access.role,"purchasing:manage",access.permissions))redirect("/overview");await placePurchaseOrder({businessId:access.business.id,orderId,userId:access.user.id});revalidatePath(`/purchasing/${orderId}`);redirect(withToast(`/purchasing/${orderId}`,"Purchase order marked as ordered."));}

export async function receivePurchaseOrderAction(formData:FormData){const parsed=z.object({orderId:z.uuid(),branchId:z.uuid(),supplierReference:optional(120),notes:optional(500),items:z.string()}).parse(Object.fromEntries(formData));const items=z.array(z.object({itemId:z.uuid(),quantity:z.number().int().min(0)})).parse(parseJson(parsed.items));const access=await requireBranchAccess(parsed.branchId);if(!hasPermission(access.role,"purchasing:manage",access.permissions))redirect("/overview");await receivePurchaseOrder({businessId:access.business.id,orderId:parsed.orderId,userId:access.user.id,supplierReference:parsed.supplierReference,notes:parsed.notes,items});revalidatePath("/inventory");revalidatePath("/purchasing");redirect(withToast(`/purchasing/${parsed.orderId}`,"Delivery received and inventory updated."));}

export async function recordPurchasePaymentAction(formData:FormData){const parsed=z.object({orderId:z.uuid(),branchId:z.uuid(),amount:z.string().regex(/^\d+(\.\d{1,2})?$/),paymentMethod:z.enum(["CASH","BANK_TRANSFER","CARD","MOBILE_MONEY","OTHER"]),reference:optional(120),notes:optional(500)}).parse(Object.fromEntries(formData));const access=await requireBranchAccess(parsed.branchId);if(!hasPermission(access.role,"purchasing:manage",access.permissions))redirect("/overview");await recordPurchasePayment({businessId:access.business.id,userId:access.user.id,orderId:parsed.orderId,amount:parseMoney(parsed.amount),paymentMethod:parsed.paymentMethod,reference:parsed.reference,notes:parsed.notes});revalidatePath(`/purchasing/${parsed.orderId}`);redirect(withToast(`/purchasing/${parsed.orderId}`,"Supplier payment recorded."));}
