import { asc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { db } from "@/db/client";
import { products } from "@/db/schema";
import { requirePermission } from "@/modules/auth/authorization";
import { listAccessibleBranches } from "@/modules/branches/queries";
import { createTransferAction } from "@/modules/transfers/actions";
export default async function NewTransferPage({searchParams}:{searchParams:Promise<{error?:string}>}){const access=await requirePermission("inventory:manage");const [branchRecords,productRecords]=await Promise.all([listAccessibleBranches({businessId:access.business.id,userId:access.user.id,role:access.role}),db.select().from(products).where(eq(products.businessId,access.business.id)).orderBy(asc(products.name))]);const{error}=await searchParams;return <><header className="topbar"><div><Link className="back-link" href="/transfers"><ArrowLeft size={15}/> Transfers</Link><h1>Create transfer</h1><p>Stock remains at source until dispatch.</p></div></header><main className="page narrow"><section className="surface"><form action={createTransferAction} className="form-stack"><div className="form-grid"><label>Source branch<select name="sourceBranchId">{branchRecords.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Destination branch<select name="destinationBranchId">{branchRecords.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Product<select name="productId">{productRecords.filter(p=>p.active&&p.trackInventory).map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" required/></label></div><label>Notes<textarea name="notes" rows={3}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><Link className="button secondary inline-button" href="/transfers">Cancel</Link><button className="button primary">Create draft</button></div></form></section></main></>}
