import { requirePermission } from "@/modules/auth/authorization";
import { updateBusinessAction } from "@/modules/businesses/actions";
import { createPaymentBankAction, togglePaymentBankAction } from "@/modules/payment-banks/actions";
import { listPaymentBanks } from "@/modules/payment-banks/queries";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string }> }) {
  const access = await requirePermission("business:manage");
  const params = await searchParams;
  const banks = await listPaymentBanks(access.business.id);
  return <><header className="topbar"><div><p className="eyebrow">Configuration</p><h1>Business settings</h1><p>Regional settings drive reports and local date boundaries.</p></div></header><main className="page narrow"><section className="surface"><form action={updateBusinessAction} className="form-stack"><div className="form-grid"><label>Business name<input name="name" defaultValue={access.business.name} required/></label><label>Currency<input value={access.business.currency} disabled/><small>Currency is locked after onboarding to protect historical amounts.</small></label><label>Timezone<input name="timezone" defaultValue={access.business.timezone} required/></label><label>Phone<input name="phone" type="tel" defaultValue={access.business.phone||""}/></label><label>Email<input name="email" type="email" defaultValue={access.business.email||""}/></label></div>{params.error&&<p className="form-error">{params.error}</p>}{params.saved&&<p className="sale-success">Settings saved.</p>}<div className="form-actions"><button className="button primary">Save settings</button></div></form></section><section className="surface" id="payment-banks"><div className="section-heading"><div><p className="eyebrow">Records</p><h2>Payment banks</h2><p className="muted">Bank accounts customers can transfer into. Selected during checkout when the payment method is bank transfer.</p></div></div>{banks.length>0&&<section className="surface table-surface report-block"><table><thead><tr><th>Bank</th><th>Branch</th><th>Account name</th><th>Account number</th><th>Status</th><th></th></tr></thead><tbody>{banks.map((bank)=><tr key={bank.id}><td><strong>{bank.bankName}</strong></td><td>{bank.branchName}</td><td>{bank.accountName}</td><td><strong>{bank.accountNumber}</strong></td><td><span className={bank.active?"pill active":"pill warning"}>{bank.active?"Active":"Inactive"}</span></td><td><form action={togglePaymentBankAction}><input type="hidden" name="bankId" value={bank.id}/><button className="table-action">{bank.active?"Deactivate":"Activate"}</button></form></td></tr>)}</tbody></table></section>}{banks.length===0&&<div className="empty-state">No payment banks yet. Add the first bank account below.</div>}<form action={createPaymentBankAction} className="form-stack count-import-form"><div className="form-grid"><label>Bank name<input name="bankName" placeholder="e.g. GTBank" required/></label><label>Bank branch<input name="branchName" placeholder="e.g. Marina" required/></label><label>Account name<input name="accountName" placeholder="e.g. Relay Market Group Ltd" required/></label><label>Account number<input name="accountNumber" placeholder="e.g. 0123456789" inputMode="numeric" pattern="[0-9]{6,30}" required/></label></div>{params.error&&<p className="form-error">{params.error}</p>}<div className="form-actions"><button className="button primary">Add payment bank</button></div></form></section></main></>;
}