import Link from "next/link";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { capabilities, commonFaqs, pricingTiers } from "@/config/marketing";
import { DashboardPreview } from "./dashboard-preview";
import { TrackedLink } from "./tracked-link";

export function PageHero({ eyebrow, title, description, preview = true }: { eyebrow: string; title: string; description: string; preview?: boolean }) { return <section className="marketing-page-hero"><div className="marketing-container page-hero-grid"><div><p className="marketing-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="marketing-lede">{description}</p><div className="marketing-button-row"><TrackedLink event="book_demo_clicked" className="marketing-button" href="/demo">Explore the Demo <ArrowRight/></TrackedLink><TrackedLink event="talk_to_sales_clicked" className="marketing-button secondary" href="/contact">Talk to Sales</TrackedLink></div></div>{preview && <DashboardPreview compact/>}</div></section>; }
export function Breadcrumbs({ items }: { items: { label: string; href?: string }[] }) { return <nav className="marketing-breadcrumbs marketing-container" aria-label="Breadcrumb"><Link href="/">Home</Link>{items.map(item => <span key={item.label}><ChevronRight/>{item.href ? <Link href={item.href}>{item.label}</Link> : <span aria-current="page">{item.label}</span>}</span>)}</nav>; }
const featureAnchors: Record<string, string> = { "Point of Sale": "point-of-sale", "Inventory Management": "inventory", "Multi-branch Management": "multi-branch", "Purchasing & Suppliers": "purchasing", "Customers & Loyalty": "customers", "Employee Management": "employee", "Finance & Expenses": "finance", "Reports & Analytics": "reports", "E-commerce Operations": "ecommerce" };

export function FeatureCollection({ limit }: { limit?: number }) { return <div className="marketing-feature-list">{capabilities.slice(0, limit).map((feature) => { const Icon = feature.icon; return <article id={featureAnchors[feature.title]} className="marketing-feature-item" key={feature.title}><div className="feature-icon"><Icon/></div><div><h3>{feature.title}</h3><p>{feature.description}</p><small>{feature.detail}</small></div></article>; })}</div>; }
export function PricingCards() { return <div className="marketing-pricing-grid">{pricingTiers.map(tier => <article className={tier.featured ? "featured" : ""} key={tier.name}>{tier.featured && <span className="pricing-badge">For growing teams</span>}<p className="marketing-eyebrow">{tier.name}</p><h3>{tier.name === "Starter" ? "Get your daily operations under control." : tier.name === "Business" ? "Give your growing team a stronger foundation." : "Bring every branch into view."}</h3><p>{tier.summary}</p><ul>{tier.features.map(f => <li key={f}><Check/>{f}</li>)}</ul><TrackedLink event="pricing_cta_clicked" href={tier.cta === "Explore the Demo" ? "/demo" : "/contact"} className={`marketing-button ${tier.featured ? "" : "secondary"}`}>{tier.cta}</TrackedLink></article>)}</div>; }
export function FAQSection({ faqs = commonFaqs }: { faqs?: readonly { question: string; answer: string }[] }) { return <section className="marketing-section faq-section"><div className="marketing-container narrow"><div className="section-intro"><p className="marketing-eyebrow">COMMON QUESTIONS</p><h2>A few things you might be wondering.</h2></div><div className="faq-list">{faqs.map((faq, i) => <details key={faq.question} open={i === 0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></div></section>; }
export function ConversionCTA() { return <section className="marketing-section"><div className="marketing-container marketing-final-cta"><div><p className="marketing-eyebrow">SEE RETAIL LOGIC IN ACTION</p><h2>Explore how control can feel in your day-to-day operations.</h2><p>Step into a safe sample workspace to explore stock, sales, branches, and team workflows at your own pace.</p></div><div className="marketing-button-row"><TrackedLink event="book_demo_clicked" className="marketing-button light" href="/demo">Explore the Demo <ArrowRight/></TrackedLink><TrackedLink event="talk_to_sales_clicked" className="marketing-button ghost" href="/contact">Talk to Sales</TrackedLink></div></div></section>; }
