import { asc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { db } from "@/db/client";
import { products } from "@/db/schema";
import { requirePermission } from "@/modules/auth/authorization";
import { listAccessibleBranches } from "@/modules/branches/queries";
import { receiveStockAction } from "@/modules/inventory/actions";

export default async function ReceivePage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const access = await requirePermission("inventory:manage"); const [branchRecords, productRecords] = await Promise.all([listAccessibleBranches({ businessId: access.business.id, userId: access.user.id, role: access.role }), db.select().from(products).where(eq(products.businessId, access.business.id)).orderBy(asc(products.name))]); const { error } = await searchParams; return <><header className="topbar"><div><Link className="back-link" href="/inventory"><ArrowLeft size={15}/> Inventory</Link><h1>Receive stock</h1><p>Confirmation creates a receipt, movement, and balance update atomically.</p></div></header><main className="page narrow"><section className="surface"><form action={receiveStockAction} className="form-stack"><div className="form-grid"><label>Branch<select name="branchId" required>{branchRecords.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Product<select name="productId" required>{productRecords.filter((p) => p.active).map((p) => <option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" required /></label><label>Unit cost<input name="unitCost" inputMode="decimal" defaultValue="0.00" required /></label><label>Supplier reference<input name="supplierReference" /></label></div><label>Notes<textarea name="notes" rows={3}/></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><Link className="button secondary inline-button" href="/inventory">Cancel</Link><button className="button primary">Confirm receipt</button></div></form></section></main></>; }
