import { asc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { PurchaseOrderForm } from "@/components/purchasing/purchase-order-form";
import { db } from "@/db/client";
import { products, suppliers } from "@/db/schema";
import { requirePermission } from "@/modules/auth/authorization";
import { listAccessibleBranches } from "@/modules/branches/queries";
export default async function NewPurchaseOrderPage({searchParams}:{searchParams:Promise<{error?:string}>}){const access=await requirePermission("purchasing:manage");const [branches,supplierRows,productRows]=await Promise.all([listAccessibleBranches({businessId:access.business.id,userId:access.user.id,role:access.role}),db.select({id:suppliers.id,name:suppliers.name}).from(suppliers).where(eq(suppliers.businessId,access.business.id)).orderBy(asc(suppliers.name)),db.select({id:products.id,name:products.name,sku:products.sku,cost:products.costPrice}).from(products).where(eq(products.businessId,access.business.id)).orderBy(asc(products.name))]);const{error}=await searchParams;if(!supplierRows.length)return <><header className="topbar"><div><Link className="back-link" href="/purchasing"><ArrowLeft size={15}/> Purchasing</Link><h1>Create purchase order</h1></div></header><main className="page narrow"><section className="surface empty-state"><p>Add a supplier before creating a purchase order.</p><Link className="button primary inline-button" href="/purchasing/suppliers/new">Add supplier</Link></section></main></>;return <><header className="topbar"><div><Link className="back-link" href="/purchasing"><ArrowLeft size={15}/> Purchasing</Link><h1>Create purchase order</h1><p>Build a reviewable draft before committing the order to your supplier.</p></div></header><main className="page"><section className="surface"><PurchaseOrderForm branches={branches} suppliers={supplierRows} products={productRows.map(x=>({...x,cost:(Number(x.cost)/100).toFixed(2)}))} error={error}/></section></main></>}
