import { desc, eq, inArray } from "drizzle-orm";
import { FileDown, Plus, Upload } from "lucide-react";
import Link from "next/link";

import { db } from "@/db/client";
import { branches, inventoryCounts, users } from "@/db/schema";
import { requirePermission } from "@/modules/auth/authorization";
import { listAccessibleBranches } from "@/modules/branches/queries";

export default async function InventoryCountsPage(){const access=await requirePermission("inventory:read");const accessible=await listAccessibleBranches({businessId:access.business.id,userId:access.user.id,role:access.role});const branchIds=accessible.map((branch)=>branch.id);const counts=branchIds.length?await db.select({id:inventoryCounts.id,countNumber:inventoryCounts.countNumber,status:inventoryCounts.status,branch:branches.name,createdBy:users.name,createdAt:inventoryCounts.createdAt,postedAt:inventoryCounts.postedAt}).from(inventoryCounts).innerJoin(branches,eq(branches.id,inventoryCounts.branchId)).innerJoin(users,eq(users.id,inventoryCounts.createdBy)).where(inArray(inventoryCounts.branchId,branchIds)).orderBy(desc(inventoryCounts.createdAt)).limit(250):[];return <><header className="topbar"><div><p className="eyebrow">Inventory control</p><h1>Inventory counts</h1><p>Snapshot, count, review, and post branch stock variances.</p></div><div className="header-actions"><a className="button secondary inline-button" href="/api/inventory/export"><FileDown size={17}/> Export inventory</a><Link className="button secondary inline-button" href="/inventory/import"><Upload size={17}/> Import inventory</Link><Link className="button primary inline-button" href="/inventory/counts/new"><Plus size={17}/> New count</Link></div></header><main className="page"><section className="surface table-surface"><table><thead><tr><th>Count</th><th>Branch</th><th>Created</th><th>Status</th><th>Posted</th></tr></thead><tbody>{counts.map((count)=><tr key={count.id}><td><Link href={`/inventory/counts/${count.id}`}><strong>{count.countNumber}</strong></Link><small>{count.createdBy}</small></td><td>{count.branch}</td><td>{count.createdAt.toLocaleString()}</td><td><span className={count.status==="POSTED"?"pill active":count.status==="REVIEW"?"pill warning":"pill"}>{count.status}</span></td><td>{count.postedAt?.toLocaleString()||"—"}</td></tr>)}</tbody></table>{!counts.length&&<div className="empty-state">No inventory counts yet.</div>}</section></main></>}
