import { asc, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { db } from "@/db/client";
import { categories } from "@/db/schema";
import { requirePermission } from "@/modules/auth/authorization";
import { createCategoryAction, createProductAction } from "@/modules/products/actions";

export default async function NewProductPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const access = await requirePermission("product:manage"); const records = await db.select().from(categories).where(eq(categories.businessId, access.business.id)).orderBy(asc(categories.name)); const { error } = await searchParams; return <><header className="topbar"><div><Link className="back-link" href="/products"><ArrowLeft size={15}/> Products</Link><h1>Create product</h1><p>Prices are stored exactly in {access.business.currency} minor units.</p></div></header><main className="page narrow"><section className="surface"><form action={createProductAction} className="form-stack"><div className="form-grid"><label>Name<input name="name" required /></label><label>SKU<input name="sku" required /></label><label>Barcode<input name="barcode" /></label><label>Category<select name="categoryId"><option value="">Uncategorised</option>{records.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Selling price<input name="sellingPrice" inputMode="decimal" placeholder="500.00" required /></label><label>Cost price<input name="costPrice" inputMode="decimal" placeholder="350.00" required /></label><label>Unit<input name="unit" defaultValue="each" required /></label><label>Minimum stock<input name="minimumStockLevel" type="number" min="0" defaultValue="5" required /></label></div><label>Description<textarea name="description" rows={3}/></label><label className="check-row"><input name="trackInventory" type="checkbox" defaultChecked/> Track branch inventory</label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><Link className="button secondary inline-button" href="/products">Cancel</Link><button className="button primary">Create product</button></div></form></section><section className="surface compact-surface"><form action={createCategoryAction} className="inline-form"><label>New category<input name="name" required /></label><button className="button secondary">Add category</button></form></section></main></>; }
