"use client";
import { Plus, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { createPurchaseOrderAction } from "@/modules/purchasing/actions";

type Product={id:string;name:string;sku:string;cost:string};
type Line={key:string;productId:string;quantity:number;unitCost:string};
export function PurchaseOrderForm({branches,suppliers,products,error}:{branches:{id:string;name:string}[];suppliers:{id:string;name:string}[];products:Product[];error?:string}){
 const[first]=products;const[lines,setLines]=useState<Line[]>([{key:"initial-line",productId:first?.id||"",quantity:1,unitCost:first?.cost||"0.00"}]);
 const total=useMemo(()=>lines.reduce((sum,line)=>sum+(Number(line.unitCost)||0)*line.quantity,0),[lines]);
 const update=(key:string,patch:Partial<Line>)=>setLines(current=>current.map(line=>line.key===key?{...line,...patch}:line));
 return <form action={createPurchaseOrderAction} className="form-stack purchasing-form"><div className="form-grid"><label>Receiving branch<select name="branchId" required>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Supplier<select name="supplierId" required>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Expected delivery<input name="expectedAt" type="date"/></label></div><section className="purchase-lines"><div className="section-heading"><div><p className="eyebrow">Order lines</p><h2>Products to order</h2></div><button type="button" className="button secondary inline-button" onClick={()=>setLines(x=>[...x,{key:crypto.randomUUID(),productId:first?.id||"",quantity:1,unitCost:first?.cost||"0.00"}])}><Plus size={16}/> Add line</button></div>{lines.map((line,index)=><div className="purchase-line" key={line.key}><label>Product<select value={line.productId} onChange={e=>{const product=products.find(x=>x.id===e.target.value);update(line.key,{productId:e.target.value,unitCost:product?.cost||"0.00"})}}>{products.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select></label><label>Quantity<input type="number" min="1" step="1" value={line.quantity} onChange={e=>update(line.key,{quantity:Number(e.target.value)})}/></label><label>Unit cost<input inputMode="decimal" value={line.unitCost} onChange={e=>update(line.key,{unitCost:e.target.value})}/></label><strong>₦{((Number(line.unitCost)||0)*line.quantity).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><button type="button" className="icon-button" aria-label={`Remove line ${index+1}`} disabled={lines.length===1} onClick={()=>setLines(x=>x.filter(y=>y.key!==line.key))}><Trash2 size={17}/></button></div>)}</section><input type="hidden" name="lines" value={JSON.stringify(lines.map(({productId,quantity,unitCost})=>({productId,quantity,unitCost})))}/><label>Order notes<textarea name="notes" rows={3} placeholder="Delivery instructions, agreed terms, or internal notes"/></label>{error&&<p className="form-error">{error}</p>}<div className="purchase-total"><span>Estimated order total</span><strong>₦{total.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="form-actions"><button className="button primary">Create draft order</button></div></form>;
}
