import { sql } from "drizzle-orm";
import { Building2, CircleDollarSign, Clock3, ShieldAlert } from "lucide-react";
import Link from "next/link";

import { db } from "@/db/client";
import { formatMoney } from "@/lib/money";

type CompanyRow = { id:string;name:string;currency:string;created_at:Date;plan_code:string;status:string;billing_interval:string;amount:string;trial_ends_at:Date|null;current_period_ends_at:Date|null;branch_limit:number|null;employee_limit:number|null;branches:number;employees:number;owner_name:string|null;owner_email:string|null };

export default async function PlatformPage({ searchParams }: { searchParams: Promise<{ q?:string; status?:string }> }) {
  const params = await searchParams;
  const rows = await db.execute<CompanyRow>(sql`select b.id,b.name,b.currency,b.created_at,coalesce(s.plan_code,'legacy') plan_code,coalesce(s.status::text,'ACTIVE') status,coalesce(s.billing_interval::text,'MANUAL') billing_interval,coalesce(s.amount,0)::text amount,s.trial_ends_at,s.current_period_ends_at,s.branch_limit,s.employee_limit,(select count(*)::int from branches br where br.business_id=b.id and br.active=true) branches,(select count(*)::int from business_memberships bm where bm.business_id=b.id and bm.active=true) employees,owner_user.name owner_name,owner_user.email owner_email from businesses b left join business_subscriptions s on s.business_id=b.id left join business_memberships owner_membership on owner_membership.business_id=b.id and owner_membership.role='OWNER' left join users owner_user on owner_user.id=owner_membership.user_id order by b.created_at desc`);
  const query=(params.q||"").trim().toLowerCase();const status=(params.status||"").toUpperCase();
  const companies=rows.filter((row)=>(!query||`${row.name} ${row.owner_name||""} ${row.owner_email||""}`.toLowerCase().includes(query))&&(!status||row.status===status));
  const active=rows.filter((row)=>row.status==="ACTIVE").length;const trials=rows.filter((row)=>row.status==="TRIALING").length;const attention=rows.filter((row)=>["PAST_DUE","SUSPENDED"].includes(row.status)).length;const mrr=rows.filter((row)=>row.status==="ACTIVE"&&row.currency==="NGN").reduce((sum,row)=>sum+(row.billing_interval==="ANNUAL"?BigInt(row.amount)/12n:row.billing_interval==="MONTHLY"?BigInt(row.amount):0n),0n);
  return <><header className="platform-hero"><div><p className="eyebrow">Owner console</p><h1>Company subscriptions</h1><p>Manage every Relay Retail tenant without entering their operational workspace.</p></div></header><main className="platform-page"><section className="metrics platform-metrics"><article><Building2/><span>Companies</span><strong>{rows.length}</strong><small>{active} active</small></article><article><Clock3/><span>Trials</span><strong>{trials}</strong><small>Currently evaluating</small></article><article><ShieldAlert/><span>Needs attention</span><strong>{attention}</strong><small>Past due or suspended</small></article><article><CircleDollarSign/><span>NGN monthly recurring</span><strong>{formatMoney(mrr,"NGN")}</strong><small>Annual plans normalised</small></article></section><section className="surface table-surface"><form className="platform-filters"><input name="q" defaultValue={params.q||""} placeholder="Search company or owner"/><select name="status" defaultValue={status}><option value="">All statuses</option>{["TRIALING","ACTIVE","PAST_DUE","SUSPENDED","CANCELED"].map((value)=><option key={value}>{value}</option>)}</select><button className="button secondary">Filter</button></form><table><thead><tr><th>Company</th><th>Owner</th><th>Plan</th><th>Usage</th><th>Period</th><th>Status</th></tr></thead><tbody>{companies.map((company)=><tr key={company.id}><td><Link href={`/platform/companies/${company.id}`}><strong>{company.name}</strong></Link><small>Created {company.created_at.toLocaleDateString()}</small></td><td>{company.owner_name||"—"}<small>{company.owner_email||"No owner email"}</small></td><td>{company.plan_code.replaceAll("_"," ")}<small>{formatMoney(BigInt(company.amount),company.currency)} · {company.billing_interval.toLowerCase()}</small></td><td>{company.branches}{company.branch_limit?` / ${company.branch_limit}`:""} branches<small>{company.employees}{company.employee_limit?` / ${company.employee_limit}`:""} employees</small></td><td>{company.current_period_ends_at?.toLocaleDateString()||company.trial_ends_at?.toLocaleDateString()||"No expiry"}</td><td><span className={`pill subscription-${company.status.toLowerCase()}`}>{company.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table>{!companies.length&&<div className="empty-state">No companies match these filters.</div>}</section></main></>;
}
