import { and, eq } from "drizzle-orm";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/db/client";
import { payments, saleItems, sales } from "@/db/schema";
import { formatMoney } from "@/lib/money";
import { requireBranchAccess, requirePermission } from "@/modules/auth/authorization";
import { voidSaleAction } from "@/modules/sales/actions";
export default async function SaleDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){const access=await requirePermission("sales:read");const{id}=await params;const[sale]=await db.select().from(sales).where(and(eq(sales.id,id),eq(sales.businessId,access.business.id))).limit(1);if(!sale)notFound();await requireBranchAccess(sale.branchId);const[items,paymentRows]=await Promise.all([db.select().from(saleItems).where(eq(saleItems.saleId,id)),db.select().from(payments).where(eq(payments.saleId,id))]);const{error}=await searchParams;return <><header className="topbar"><div><Link className="back-link" href="/sales"><ArrowLeft size={15}/> Sales</Link><h1>{sale.saleNumber}</h1><p>{sale.status} · {sale.completedAt.toLocaleString()}</p></div><strong>{formatMoney(sale.total,access.business.currency)}</strong></header><main className="page narrow"><section className="surface table-surface"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.productNameSnapshot}</strong><small>{i.skuSnapshot}</small></td><td>{i.quantity}</td><td>{formatMoney(i.unitPrice,access.business.currency)}</td><td>{formatMoney(i.lineTotal,access.business.currency)}</td></tr>)}</tbody></table></section><section className="surface compact-surface"><h2>Payments</h2>{paymentRows.map(p=><div className="payment-row" key={p.id}><span>{p.paymentMethod.replaceAll("_"," ")} · {p.status}</span><strong>{formatMoney(p.amount,access.business.currency)}</strong></div>)}</section>{sale.status==="COMPLETED"&&(access.role==="OWNER"||access.role==="ADMIN")&&<section className="surface compact-surface danger-zone"><h2>Void completed sale</h2><p className="muted">This restores tracked inventory, marks payments refunded, and preserves the original sale.</p><form action={voidSaleAction} className="form-stack"><input type="hidden" name="saleId" value={sale.id}/><label>Reason<textarea name="reason" minLength={5} required/></label>{error&&<p className="form-error">{error}</p>}<button className="button danger-button">Void and reverse sale</button></form></section>}</main></>}
