import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Check, CircleDollarSign, MapPin, PackageCheck, ShieldCheck, UsersRound } from "lucide-react";
import { DashboardPreview } from "@/components/marketing/dashboard-preview";
import { ConversionCTA, FeatureCollection, PricingCards } from "@/components/marketing/sections";
import { TrackedLink } from "@/components/marketing/tracked-link";
import { industries } from "@/config/marketing";

export const metadata: Metadata = { title: "Retail Logic | Retail Management and Operations Software", description: "Manage sales, inventory, customers, employees, suppliers, expenses, multiple branches, and e-commerce operations with Retail Logic.", alternates: { canonical: "/" }, openGraph: { title: "One platform to run your entire retail business", description: "Complete visibility and control across every store and sales channel.", url: "/" } };

const branches = [["Lagos Island", "₦1.42m", "386", "Online"], ["Ikeja", "₦1.18m", "319", "Online"], ["Lekki", "₦1.56m", "402", "Top branch"], ["Abuja", "₦660k", "177", "Online"]];
const inventory = [["Golden Penny Flour 5kg", "GDF-500", "Lagos Island", "8", "12", "Low"], ["Peak Milk 400g", "PMK-400", "Ikeja", "42", "18", "Healthy"], ["Sunlight Detergent 1kg", "SDL-100", "Lekki", "0", "10", "Out"], ["Royal Stallion Rice 10kg", "RSR-010", "Abuja", "31", "15", "Healthy"]];

export default function MarketingHome() { return <>
  <section className="marketing-hero"><div className="marketing-container hero-grid"><div className="hero-copy"><p className="marketing-eyebrow">RETAIL OPERATIONS, UNIFIED</p><h1>One platform to run your entire retail business.</h1><p className="marketing-lede">Know what sold. See what is running low. Keep your team accountable. Retail Logic brings sales, stock, cash, and branch performance together so you can make decisions with confidence.</p><div className="marketing-button-row"><TrackedLink event="book_demo_clicked" href="/book-demo" className="marketing-button">Book a Demo <ArrowRight/></TrackedLink><Link href="/features" className="marketing-button secondary">Explore the Platform</Link></div><p className="hero-trust"><Check/> Built for supermarkets, stores, malls, wholesalers, and e-commerce businesses.</p></div><div className="hero-visual"><DashboardPreview/><span className="float-note note-one">Sales up <b>18.4%</b></span><span className="float-note note-two"><i/> All branches online</span></div></div></section>
  <section className="industry-strip"><div className="marketing-container"><p>Built for modern retail operations</p><div>{industries.map(x => <span key={x}>{x}</span>)}</div></div></section>
  <section className="marketing-section visibility-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">OPERATIONAL VISIBILITY</p><h2>Know how your business is doing—without chasing updates.</h2></div><p>When sales, stock, and cash records live in different places, problems are easy to miss. Bring the numbers together and give every management decision a clearer starting point.</p></div><div className="visibility-board"><div className="board-sidebar"><strong>Performance</strong>{["Overview", "Sales", "Inventory", "Expenses", "Customers"].map((x,i)=><span className={i===0?"active":""} key={x}>{x}</span>)}</div><div className="board-main"><div className="board-filters"><span>Aug 1 – Aug 30</span><span>All branches</span></div><div className="board-kpis"><span><small>Net revenue</small><b>₦4.82m</b></span><span><small>Inventory value</small><b>₦8.14m</b></span><span><small>Expenses</small><b>₦640k</b></span></div><div className="board-chart"><div><small>Revenue by location</small><strong>Current period</strong></div>{branches.map((b,i)=><div className="bar-row" key={b[0]}><span>{b[0]}</span><i style={{"--bar": `${92-i*14}%`} as React.CSSProperties}/><b>{b[1]}</b></div>)}</div></div></div><div className="benefit-row"><span><BarChart3/><b>Real-time visibility</b>See the latest operating picture.</span><span><ShieldCheck/><b>Centralized control</b>Standardize teams and locations.</span><span><CircleDollarSign/><b>Actionable reporting</b>Move from numbers to decisions.</span></div></div></section>
  <section className="marketing-section capabilities-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">ONE CONNECTED PLATFORM</p><h2>Keep the sale, the stock, and the numbers connected.</h2></div><p>A sale should update your stock. A transfer should leave a record. A manager should know who did what. Give your team a consistent way to work from checkout to closing.</p></div><FeatureCollection/></div></section>
  <section className="marketing-section steps-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">HOW IT WORKS</p><h2>From setup to daily control in three clear steps.</h2></div><ol className="steps"><li><h3>Set up your business</h3><p>Add stores, products, employees, suppliers, and business settings.</p></li><li><h3>Connect your operations</h3><p>Bring sales, inventory, customers, expenses, and locations into one system.</p></li><li><h3>Run with complete visibility</h3><p>Monitor performance, identify problems, and make faster decisions.</p></li></ol></div></section>
  <section className="marketing-section inventory-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">INVENTORY INTELLIGENCE</p><h2>Keep your best sellers on the shelf. Know where your stock went.</h2></div><p>Check quantities before you reorder, investigate stock differences, and follow transfers between branches. Make replenishment decisions with a clearer picture of what you already have.</p></div><div className="inventory-toolbar"><span>Inventory value <b>₦8,140,600</b></span><span>Fast-moving <b>86 products</b></span><span>Slow-moving <b>24 products</b></span><button>New stock transfer</button></div><div className="marketing-table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Branch</th><th>Quantity</th><th>Reorder at</th><th>Status</th></tr></thead><tbody>{inventory.map(row=><tr key={row[1]}>{row.map((v,i)=><td key={i}>{i===5?<span className={`stock-status ${v.toLowerCase()}`}>{v}</span>:v}</td>)}</tr>)}</tbody></table></div></div></section>
  <section className="marketing-section branches-section"><div className="marketing-container branch-layout"><div><p className="marketing-eyebrow">MULTI-LOCATION OPERATIONS</p><h2>Every location. One source of truth.</h2><p>See which branches are selling, where stock needs attention, and how teams are performing. Stay close to the business even when you cannot be in every store.</p><ul><li><Check/> Branch-level employee access</li><li><Check/> Traceable inventory transfers</li><li><Check/> Consolidated operational reporting</li></ul></div><div className="branch-board"><div className="branch-board-head"><span><MapPin/> Branch performance</span><small>Sample operational data</small></div>{branches.map((b,i)=><div className="branch-row" key={b[0]}><span><i className="branch-dot"/>{b[0]}</span><strong>{b[1]}</strong><span>{b[2]} sales</span><em className={i===2?"top":""}>{b[3]}</em></div>)}</div></div></section>
  <section className="marketing-section loyalty-section"><div className="marketing-container loyalty-layout"><div className="customer-card"><div className="customer-head"><span>AO</span><div><strong>Customer profile</strong><small>Returning customer · Lagos</small></div></div><div className="customer-stats"><span><small>Lifetime value</small><b>₦286,400</b></span><span><small>Loyalty points</small><b>1,860</b></span><span><small>Purchases</small><b>24</b></span></div><div className="retention"><span>Returning customers <b>38%</b></span><i><b/></i></div></div><div><p className="marketing-eyebrow">CUSTOMERS & LOYALTY</p><h2>Turn transactions into lasting customer relationships.</h2><p>Keep purchase history, loyalty points, visit frequency, lifetime value, and useful customer segments in one view.</p><Link className="marketing-arrow-link" href="/features#customers">Explore customer tools <ArrowRight/></Link></div></div></section>
  <section id="reports" className="marketing-section reports-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">REPORTING</p><h2>Turn the day’s numbers into tomorrow’s decisions.</h2><p>Which products earn their shelf space? Where are stock differences building up? How did each cashier perform? Use sales, margin, and stock reports to ask better questions and act sooner.</p></div><div className="report-cloud">{["Daily sales","Profit & margin","Inventory movement","Low stock","Cashier performance","Expenses","Customer retention","Branch comparison","Product performance"].map((x,i)=><span className={`r${i}`} key={x}>{x}</span>)}</div></div></section>
  <section className="marketing-section security-section"><div className="marketing-container security-layout"><div><p className="marketing-eyebrow">CONTROL & ACCOUNTABILITY</p><h2>Built for control, accountability, and growth.</h2></div><div className="security-list">{[[ShieldCheck,"Role-based permissions","Give each employee defined operational access."],[UsersRound,"Branch-level access","Keep teams focused on assigned locations."],[PackageCheck,"Transaction traceability","Follow sales and stock movements through clear records."],[BarChart3,"Activity logs","Review important actions and changes."]].map(([Icon,title,text])=><article key={String(title)}><Icon/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></article>)}</div></div></section>
  <section className="marketing-section testimonial-section"><div className="marketing-container"><p className="marketing-eyebrow">START WITH YOUR BIGGEST OPERATIONAL CHALLENGE</p><h2>What would you like to get under control first?</h2><p>Stock differences. Credit balances. Cashier records. Branch reporting.</p><p>Bring one real challenge to your demo and see the relevant workflow in action.</p><TrackedLink event="book_demo_clicked" href="/book-demo" className="marketing-button">Book a Demo <ArrowRight/></TrackedLink></div></section>
  <section className="marketing-section pricing-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">PRICING</p><h2>A plan that fits the way you operate.</h2><p>Start with the workflows you need today, with room for more people and locations as your business grows. Tell us about your operation and get a tailored proposal.</p></div><PricingCards/></div></section>
  <ConversionCTA/>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Organization","name":"Retail Logic","url":"/","logo":"/brand/retail-logic-app-icon.png"},{"@type":"WebSite","name":"Retail Logic","url":"/"},{"@type":"SoftwareApplication","name":"Retail Logic","applicationCategory":"BusinessApplication","operatingSystem":"Web","description":"Retail management and operations software for sales, inventory, customers, employees, and multiple branches."}]})}}/>
 </>; }
