import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BarChart3, Check, CircleDollarSign, Sparkles, PackageCheck, ShieldCheck, UsersRound } from "lucide-react";
import { DashboardPreview } from "@/components/marketing/dashboard-preview";
import { ConversionCTA, FeatureCollection, PricingCards } from "@/components/marketing/sections";
import { TrackedLink } from "@/components/marketing/tracked-link";
import { industries } from "@/config/marketing";

export const metadata: Metadata = { title: "Retail Logic | Retail Management and Operations Software", description: "Manage sales, inventory, customers, employees, suppliers, expenses, multiple branches, and e-commerce operations with Retail Logic.", alternates: { canonical: "/" }, openGraph: { title: "One platform to run your entire retail business", description: "Complete visibility and control across every store and sales channel.", url: "/" } };

export default function MarketingHome() { return <>
  <section className="marketing-hero"><div className="marketing-container hero-grid"><div className="hero-copy"><p className="marketing-eyebrow">A LITTLE LESS BUSY. A LOT MORE CLARITY.</p><h1>Your store, running <span>beautifully.</span></h1><p className="marketing-lede">Big plans. Busy tills. Lots to keep track of. Bring your sales, stock, and team together with Retail Logic — and make a little more room for what you love about your business.</p><div className="marketing-button-row"><TrackedLink event="book_demo_clicked" href="/demo" className="marketing-button">Explore the Demo <ArrowRight/></TrackedLink><Link href="/features" className="marketing-button secondary">Explore the Platform</Link></div><p className="hero-trust"><Check/> Built for supermarkets, stores, malls, wholesalers, and e-commerce businesses.</p></div><div className="hero-visual"><div className="hero-sticker"><Sparkles/> Hello, calmer workdays.</div><DashboardPreview/><Image className="hero-shopkeeper" src="/brand/shopkeeper.png" width={1024} height={1536} alt="" sizes="(max-width: 680px) 130px, 240px" preload/><span className="hero-doodle" aria-hidden="true">✳</span></div></div></section>
  <section className="industry-strip"><div className="marketing-container"><p>Built for modern retail operations</p><div>{industries.map(x => <span key={x}>{x}</span>)}</div></div></section>
  <section className="marketing-section visibility-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">OPERATIONAL VISIBILITY</p><h2>Your day at a glance. Your next move, clearer.</h2></div><p>When sales, stock, and cash records live in different places, problems are easy to miss. Bring the numbers together and give every management decision a clearer starting point.</p></div><div className="product-stage"><DashboardPreview/></div><div className="benefit-row"><span><BarChart3/><b>Real-time visibility</b>See the latest operating picture.</span><span><ShieldCheck/><b>Centralized control</b>Standardize teams and locations.</span><span><CircleDollarSign/><b>Actionable reporting</b>Move from numbers to decisions.</span></div></div></section>
  <section className="marketing-section capabilities-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">ONE CONNECTED PLATFORM</p><h2>Keep the sale, the stock, and the numbers connected.</h2></div><p>A sale should update your stock. A transfer should leave a record. A manager should know who did what. Give your team a consistent way to work from checkout to closing.</p></div><FeatureCollection/></div></section>
  <section className="marketing-section steps-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">HOW IT WORKS</p><h2>Let’s get your store into its rhythm.</h2></div><ol className="steps"><li><h3>Set up your business</h3><p>Add stores, products, employees, suppliers, and business settings.</p></li><li><h3>Connect your operations</h3><p>Bring sales, inventory, customers, expenses, and locations into one system.</p></li><li><h3>Run with complete visibility</h3><p>Monitor performance, identify problems, and make faster decisions.</p></li></ol></div></section>
  <section className="marketing-section inventory-section"><div className="marketing-container"><div className="section-intro split"><div><p className="marketing-eyebrow">INVENTORY INTELLIGENCE</p><h2>Happy shelves. Fewer stock surprises.</h2></div><p>Check quantities before you reorder, investigate stock differences, and follow transfers between branches. Make replenishment decisions with a clearer picture of what you already have.</p></div><div className="product-stage inventory-stage"><DashboardPreview screen="inventory"/></div></div></section>
  <section className="marketing-section branches-section"><div className="marketing-container branch-layout"><div><p className="marketing-eyebrow">MULTI-LOCATION OPERATIONS</p><h2>More stores. Still in the loop.</h2><p>See which branches are selling, where stock needs attention, and how teams are performing. Stay close to the business even when you cannot be in every store.</p><ul><li><Check/> Branch-level employee access</li><li><Check/> Traceable inventory transfers</li><li><Check/> Consolidated operational reporting</li></ul></div><DashboardPreview screen="branches"/></div></section>
  <section id="reports" className="marketing-section reports-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">REPORTING</p><h2>Turn the day’s numbers into tomorrow’s decisions.</h2><p>Which products earn their shelf space? Where are stock differences building up? How did each cashier perform? Use sales, margin, and stock reports to ask better questions and act sooner.</p></div><div className="report-cloud">{["Daily sales","Profit & margin","Inventory movement","Low stock","Cashier performance","Expenses","Customer retention","Branch comparison","Product performance"].map((x,i)=><span className={`r${i}`} key={x}>{x}</span>)}</div></div></section>
  <section className="marketing-section security-section"><div className="marketing-container security-layout"><div><p className="marketing-eyebrow">CONTROL & ACCOUNTABILITY</p><h2>Built for control, accountability, and growth.</h2></div><div className="security-list">{[[ShieldCheck,"Role-based permissions","Give each employee defined operational access."],[UsersRound,"Branch-level access","Keep teams focused on assigned locations."],[PackageCheck,"Transaction traceability","Follow sales and stock movements through clear records."],[BarChart3,"Activity logs","Review important actions and changes."]].map(([Icon,title,text])=><article key={String(title)}><Icon/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></article>)}</div></div></section>
  <section className="marketing-section testimonial-section"><div className="marketing-container"><p className="marketing-eyebrow">START WITH YOUR BIGGEST OPERATIONAL CHALLENGE</p><h2>What would you like to get under control first?</h2><p>Stock differences. Credit balances. Cashier records. Branch reporting.</p><p>Explore the sample workspace and see the relevant workflows in action.</p><TrackedLink event="book_demo_clicked" href="/demo" className="marketing-button">Explore the Demo <ArrowRight/></TrackedLink></div></section>
  <section className="marketing-section pricing-section"><div className="marketing-container"><div className="section-intro"><p className="marketing-eyebrow">PRICING</p><h2>A plan that fits the way you operate.</h2><p>Start with the workflows you need today, with room for more people and locations as your business grows. Tell us about your operation and get a tailored proposal.</p></div><PricingCards/></div></section>
  <ConversionCTA/>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Organization","name":"Retail Logic","url":"/","logo":"/brand/retail-logic-app-icon.png"},{"@type":"WebSite","name":"Retail Logic","url":"/"},{"@type":"SoftwareApplication","name":"Retail Logic","applicationCategory":"BusinessApplication","operatingSystem":"Web","description":"Retail management and operations software for sales, inventory, customers, employees, and multiple branches."}]})}}/>
 </>; }
